#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.demo.dao
  mapperLocations: classpath*:com/example/demo/**/*Mapper.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.1.11:3306/test?useUnicode=true&&characterEncoding=UTF-8
    username: admin
    password: admin1320
    driver-class-name: com.mysql.jdbc.Driver